Use this cell for all your imports

In [21]:
import numpy as np
from scipy.linalg.blas import dgemv, ddot, dnrm2
import scipy.linalg.blas as blas
import scipy.linalg as la

Create a matrix and a vector using NumPy.Their dtype should be double.

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
x = np.array([1, 2, 3], dtype=np.double)

Use BLAS functions to perform matrix-vector multiplication

In [3]:
y = np.zeros_like(x)
alpha = 1.0
beta = 0.0
dgemv(alpha, A, x, beta, y)
print(y)

[0. 0. 0.]




Create two new vectors and calculate their dot product using BLAS functions.


In [5]:
a = np.array([1, 2, 3], dtype=np.double)
b = np.array([4, 5, 6], dtype=np.double)
result = ddot(a, b)
print(result)

32.0


Compute the L2 norm (Euclidean distance) of a vector using BLAS functions

In [6]:
a = np.array([1, 2, 3], dtype=np.double)
norm = dnrm2(a)
print(norm)

3.7416573867739413


Create a 5x5 symmetric matrix and calculate its eigenvalues and eigenvectors using BLAS functions

In [13]:
import scipy
print(scipy.__version__)""
# checking the version of my scipy because the dsyev function doesn't wanna work, i will replace it using "eigh"

1.10.1


In [14]:
from scipy.linalg import eigh

In [15]:
A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]], dtype=np.double)
w, v = eigh(A)
print("Eigenvalues:", w)
print("Eigenvectors:", v)

Eigenvalues: [-0.51572947  0.17091519 11.34481428]
Eigenvectors: [[ 0.73697623  0.59100905 -0.32798528]
 [ 0.32798528 -0.73697623 -0.59100905]
 [-0.59100905  0.32798528 -0.73697623]]


Given the following matrix A and vector v:

In [16]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
b = np.array([1, 2, 3], dtype=np.double)

Solve the system Ax = b using the LU decomposition method and BLAS functions

In [22]:
# Define the matrix A and the vector b like in the exercice

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
b = np.array([1, 2, 3], dtype=np.double)

# Compute the LU decomposition of A
lu, piv = la.lu_factor(A)

# Solve the system Ax = b using the LU factors
x = la.lu_solve((lu, piv), b)

# Verify the solution by computing Ax
Ax = blas.dgemv(1.0, A, x)

# Print the solution and verify that Ax = b
print("x =", x)
print("Ax =", Ax)
print("b =", b)


x = [1. 1. 1.]
Ax = [1.00000000e+00 1.11022302e-16 1.00000000e+00]
b = [1 0 1]
